language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.4
      env: DB=oracle
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mysql EXTERNAL=true
  allow_failures:
    - php: hhvm
  fast_finish: true

env:
  global:
    - EXTERNAL=false
    - secure: "HB1kkN7ExwlXsMduf3h6r+a8GeXobtTcuwGNQCkHICaAG+XQKK0CtuPKQkEa0o0kaYio4UoUcqkEQa3Ej+xpnlCLdfZbyfLFGyM1CxTvnSg2lZENXHAzQ2W2hwGgc1b6jPYGUWIv6GVjNB0sCu6Gz2Y/DHnEpr9FBd9Rdxed6SE="
    - secure: "toor9TGKVBSl0O9ATwdozJpv0vqGcD7eqpH0KQ/Os3NXNECfldHmgiq3fGy7YP8qb05awHJ0TXuj4Lwmu7EfxWG8r9RnpnE+rq+cZ6HCp4OZD9Feo4TeMOyc/8R1FkRt5v7KOqALMlc1QoAMsnBw9vpJRCYIlQmp18qR5ZgrWfk="
  matrix:
    - DB=sqlite

before_install:
- sudo apt-get update
- mkdir -p buildout-cache/downloads
- python build/bootstrap.py
- build/bin/buildout -N -t 3
- sudo apt-get install apache2 libapache2-mod-fastcgi
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
- sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
- sudo service apache2 restart
- mkdir -p build/parts/test/

before_script:
  # setup databases
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/setup_databases.sh
  - bash ./setup_databases.sh $DB

  # Additional PHP config
  - if [[ $HHVM == false ]] ; then phpenv config-add build/travis.php.ini ; fi

  # fetch Ocular (for test coverage upload)
  - wget https://scrutinizer-ci.com/ocular.phar

  # call setup for tests
  - build/prepareTests.sh $DB

  # Enable/disable files_external to control it's unit test execution
  - php occ --list
  - if [[ $EXTERNAL == true ]] ; then php occ app:enable files_external ; fi
  - if [[ $EXTERNAL == false ]] ; then php occ app:disable files_external ; fi

  # Enable display for robotframework tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - phpunit --version
  # Run PHP lint for each PHP version
  - if [[ $DB == 'sqlite' ]] ; then ant -f build/build.xml -Dbasedir=. prepare lint ; fi

  # Run tests
  - phpunit --configuration tests/phpunit-autotest.xml --coverage-clover tests/autotest-clover-$DB.xml --verbose --debug

  # Run JS tests just once (see test matrix - mysql is just run once)
  - if [[ $DB == 'mysql' ]] ; then ./autotest-js.sh ; fi

  # Upload coverage report
  - php ocular.phar code-coverage:upload --format=php-clover tests/autotest-clover-$DB.xml

  # Run robot tests
  - ./builds/bin/pybot -d build/parts/test tests/robot

after_success:
  - cd build/parts/test/
  - find -type f -exec curl -v -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ci.owncloud.com/robotframework/{} \;

branches:
  only:
    - master
    - stable5
    - stable6
    - stable7
